srqservermake: 
	g++ srq_server.cpp -pthread -o srqserver

srqclientmake: 
	g++ srq_client.cpp -pthread -o srqclient

gbnservermake:
	g++ gbn_server.cpp -pthread -o gbnserver

gbnclientmake:
	g++ gbn_client.cpp -pthread -o gbnclient

clean:
	rm -f srqserver srqclient gbnserver gbnclient *.out